---
title: "Assignment 1a"
author: "Genevieve Chiong"
date: "2/7/2022"
output:
  prettydoc::html_pretty:
    theme: hpstr
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Why I am taking this course
ESM 206 was my introduction to data science and I enjoyed it so much that I enrolled in ESM 244, and now this course. In my mind, I can see an end goal for the data and I like the challenge of solving the puzzle of how to reach that end. I like how mentally stimulating coding is. I am hoping to pursue a career in data science after graduating and feel like I need to practice as much as possible because I find that coding is very easy to forget once it's not being used. I'm hoping to gain as much data science experience as I can while I'm at Bren.


## My data science background
I learned how to code for the first time at Bren, taking ESM 206 and 244. Last summer, I interned with USDA's National Agricultural Statistics Service where I built web scrapers in R to collect, process, and store external data for grape producers in California for the 2021 Grape Crush Report. I also utilized R to validate and analyze spatial data of agricultural land in California and Nevada to support a national study assessing agricultural land usage. 
