---
title: "Extreme Temperature Risk for Wheat Crops"
author: "Genevieve Chiong"
date: "3/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(kableExtra)

source(here("R/wheat_temperature.R"))
```


```{r, message = FALSE}
# read in the temperature data
tmax <- read_delim(here("data", "tmax.txt"), delim = " ")

# create random data for age 
age = runif(min = 1, max = 12, n = 7920) 
```



```{r}
# use wheat_temperature function
risk <- wheat_temperature(daily_temp = tmax$tmax, age = age) 

# view results
risk
```
**The number of extreme events (when daily temperature >= 28 C) is 1,257.**

```{r}
# view results in a table
risk_table <- risk %>% 
  as.data.frame() %>% 
  cbind(wheat_age = age) %>%
  cbind(tmax = tmax$tmax) %>%
  select(-n_extremes)

kable(risk_table,
      col.names = c("Risk",
                    "Wheat Age",
                    "Tmax")) %>% 
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE)
```



