---
title: "Looping Exercise"
author: "Genevieve Chiong"
date: "2/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
library(ggpubr)
library(here)

source(here("R/auto_power_gen.R"))
```


# Our highway

4 Car Types 

* Car A: mass = 20000 kg, area = 22 m^2^
* Car B: mass = 65000 kg, area = 30 m^2^ 
* Car C: mass = 38000 kg, area = 22 m^2^
* Car D: mass = 5000 kg, area = 10 m^2^

Mean highway speed = 100 km/hr 

```{r}
# generate a structure to store info on our possible cars
possible_cars <- data.frame(name = c("A", "B", "C", "D"), 
                            mass = c(20000, 65000, 38000, 5000), 
                            area = c(22, 30, 22, 10))
```

```{r}
# use sample to generate a distribution of speeds
# assume a log normal distribution of speeds with mean 100 km/hr and standard deviation that is 10% of the mean

nsample = 200
mean_speed = log(100*0.277)

speeds = rlnorm(mean = mean_speed,
                sd = 0.1 * mean_speed,
                nsample)

plot(density(speeds),
     ylab = "Distribution of Speeds in (m/s)")
```

# By hand 
```{r, results = FALSE}
# run each car for all speeds 

# car a 
powerA = auto_power_gen(V = speeds, A = possible_cars$area[1], m = possible_cars$mass[1])
summary(powerA)

# car b 
powerB = auto_power_gen(V = speeds, A = possible_cars$area[2], m = possible_cars$mass[2])
summary(powerB)

# car c 
powerC = auto_power_gen(V = speeds, A = possible_cars$area[3], m = possible_cars$mass[3])
summary(powerC)

# car d
powerD = auto_power_gen(V = speeds, A = possible_cars$area[4], m = possible_cars$mass[4])
summary(powerD)

# combine into one dataframe and pivot_longer
powerall1 <- cbind.data.frame(powerA, powerB, powerC, powerD)
colnames(powerall1) = possible_cars$name

powerallr1 <- powerall1 %>% 
  pivot_longer(cols = everything(), 
               names_to = "car", 
               values_to = "power")

method1_plot <- ggplot(data = powerallr1,
                        aes(x = car,
                            y = power, 
                            fill = car)) +
  geom_boxplot() + 
  ggtitle("By Hand")

method1_plot
```

# Pmap

```{r}
nsample = 200
mean_speed = log(100*0.277)

speeds = rlnorm(mean = mean_speed,
                sd = 0.1 * mean_speed,
                nsample)

plot(density(speeds),
     ylab = "Distribution of Speeds in (m/s)")
```

```{r}
powerall2 <- pmap(list(A = possible_cars$area, m=possible_cars$mass), 
                  auto_power_gen, 
                  V=speeds)

# turn into a data frame
powerall2 <- as.data.frame(powerall2, col.names = possible_cars$name)

# turn columns into rows 
powerallr2 <- powerall2 %>% pivot_longer(cols = everything(),
                                         names_to = "car",
                                         values_to = "power")

method2_plot <-  ggplot(data = powerallr2, 
                        aes(x = car,
                            y = power, 
                            fill=car)) + 
  geom_boxplot() + 
  ggtitle("Pmap")

method2_plot
```


# For Loop

```{r}
nsample = 200
mean_speed = log(100*0.277)

speeds = rlnorm(mean = mean_speed,
                sd = 0.1 * mean_speed,
                nsample)

plot(density(speeds),
     ylab = "Distribution of Speeds in (m/s)")
```

```{r, results = FALSE}
# create a data frame to store results
powerall3 <- as.data.frame(matrix(nrow = length(speeds),
                                  ncol = nrow(possible_cars)))
nrow(possible_cars)

for(i in 1:nrow(possible_cars)) {
  powerall3[i] = auto_power_gen(A = possible_cars$area[i], m = possible_cars$mass[i], V = speeds)
}

# add column names
colnames(powerall3) = possible_cars$name

# turn columns into rows 
powerallr3 <- powerall3 %>% pivot_longer(cols = everything(),
                                        names_to = "car", 
                                        values_to = "power")

method3_plot <- ggplot(data = powerallr3, 
                       aes(x = car,
                           y = power, 
                           fill = car)) + 
  geom_boxplot() +
  ggtitle("For Loop")

method3_plot
```


```{r}
# by hand summary
summary(powerall1)

# pmap summary
summary(powerall2)

# for loop summary
summary(powerall3)
```

# Results 

### By Hand 

* Car A: Mean = 225000   
* Car B: Mean = 468503   
* Car C: Mean = 302141   
* Car D: Mean = 84741

### Pmap

* Car A: Mean = 219795   
* Car B: Mean = 461887   
* Car C: Mean = 297166   
* Car D: Mean = 82322 

### For Loop

* Car A: Mean = 228416  
* Car B: Mean = 475804   
* Car C: Mean = 306818  
* Car D: Mean = 86007 


```{r, echo = FALSE}
method1_plot
method2_plot
method3_plot
```






